version: "3"

services:
  app-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONFIG_NAME: "DevelopmentConfig"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@pg:5432/library"
    ports:
      - "5050:5000"
    volumes:
      - ./:/app/
    depends_on:
      - pg

  app-prod:
    build:
      context: .
      dockerfile: docker-build/Dockerfile
    environment:
      CONFIG_NAME: "ProductionConfig"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@pg:5432/library"
    ports:
      - "5080:80"
    depends_on:
      - pg

  pg:
    image: postgres:14
    env_file: "postgres.env"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/
volumes:
  pg-data:
#    name: homework-06-pg-data


